syntax = "proto3";

package identity;

service IdentityService {
  rpc GetUser (GetUserRequest) returns (UserResponse);
  rpc GetUsersByIds (GetUsersByIdsRequest) returns (UsersResponse);
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);
}

message GetUserRequest {
  string user_id = 1;
}

message GetUsersByIdsRequest {
  repeated string user_ids = 1;
}

message UserResponse {
  string id = 1;
  string first_name = 2;
  string last_name = 3;
  string email = 4;
  string status = 5;
}

message UsersResponse {
  repeated UserResponse users = 1;
}

message ValidateTokenRequest {
  string access_token = 1;
}

message ValidateTokenResponse {
  bool valid = 1;
  string user_id = 2;
  string email = 3;
}
